CREATE TABLE ingredients
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_ingredients PRIMARY KEY (id)
);

ALTER TABLE ingredients
    ADD CONSTRAINT uc_ingredients_name UNIQUE (name);

CREATE TABLE glasses
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    size INTEGER                                 NOT NULL,
    CONSTRAINT pk_glasses PRIMARY KEY (id)
);

ALTER TABLE glasses
    ADD CONSTRAINT uc_glasses_name UNIQUE (name);

INSERT INTO glasses (name, size)
VALUES ('Rocks Glass', 300),
       ('Collins Glass', 350),
       ('Highball Glass', 400),
       ('Martini Glass', 150),
       ('Champagne Flute', 180),
       ('Coupe Glass', 200),
       ('Shot Glass', 50),
       ('Hurricane Glass', 450),
       ('Margarita Glass', 250),
       ('Pilsner Glass', 500),
       ('Wine Glass', 250),
       ('Mason Jar', 400);

INSERT INTO ingredients (name)
VALUES ('Vodka'),
       ('Rum'),
       ('Gin'),
       ('Tequila'),
       ('Whiskey'),
       ('Brandy'),
       ('Triple Sec'),
       ('Lime Juice'),
       ('Lemon Juice'),
       ('Orange Juice'),
       ('Cranberry Juice'),
       ('Pineapple Juice'),
       ('Grenadine'),
       ('Simple Syrup'),
       ('Cola'),
       ('Soda Water'),
       ('Tonic Water'),
       ('Ginger Beer'),
       ('Bitters'),
       ('Mint Leaves'),
       ('Sugar'),
       ('Salt'),
       ('Ice');